### ISSUE TITLE
installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by avilella** [Molmed/checkQC#36]
Are there installation instructions for Ubuntu 14.04?

I tried, but:

```
sudo pip install -f https://github.com/Illumina/interop/releases/tag/v1.1.1 interop
Downloading/unpacking interop
  Could not find a version that satisfies the requirement interop (from versions: 1.1.1-Darwin-AppleClang, 1.1.1-Linux-GNU, 1.1.1-Windows-MSVC)
Cleaning up...
No distributions matching the version for interop
Storing debug log for failure in /home/avilella/.pip/pip.log
```

**Comment by johandahlberg** [comment]
Hi @avilella!

Thank you for reporting this issue. I've been able to reproduce it in a virtual machine. The problem seems to be that checkqc requires a python version greater than 3.5. I'll make sure that this information is added to the README.

I followed this guide to [install python3.5](https://askubuntu.com/questions/682869/how-do-i-install-a-different-python-version-using-apt-get). And then I created a virtual environment with python3.5 to install checkqc into.

I then installed pip and created a virtual environment using python 3.5 to run checkqc, and this appears to work:

```
sudo apt-get install python3-pip
sudo pip3 install virtualenv
virtualenv --python=python3.5 venv-py3.5
source venv-py3.5/bin/activate
pip install -f https://github.com/Illumina/interop/releases/tag/v1.1.1 interop
pip install checkqc
checkqc --version
```
Does this work for you? I'll make sure to update the documentation accordingly.

**Comment by avilella** [comment]
Thanks for the quick reply.

I will follow the instructions and see if this sorts things out.

A.

**Comment by avilella** [comment]
I tried the commands above on an Ubuntu 14.04 instance via DNAnexus
Makefile to build an asset, but the vitualenv --python command didn't seem
to work. See below.

Any ideas?

2017-11-16 06:50:32 asset_checkqc STDOUT sudo pip3 install virtualenv
2017-11-16 06:50:32 asset_checkqc STDOUT Downloading/unpacking virtualenv
2017-11-16 06:50:32 asset_checkqc STDOUT Installing collected packages:
virtualenv
2017-11-16 06:50:32 asset_checkqc STDOUT Successfully installed virtualenv
2017-11-16 06:50:32 asset_checkqc STDOUT Cleaning up...
2017-11-16 06:50:32 asset_checkqc STDOUT virtualenv --python=python3.5
venv-py3.5
2017-11-16 06:50:32 asset_checkqc STDOUT The path python3.5 (from
--python=python3.5) does not exist
2017-11-16 06:50:32 asset_checkqc STDOUT make: Leaving directory
`/home/dnanexus'
2017-11-16 06:50:32 asset_checkqc STDOUT

**Comment by avilella** [comment]
It turns out Ubuntu 14.04 has python3.4, changed it now, works at this step
but gets stuck at installing interop:

2017-11-16 07:09:24 asset_checkqc STDOUT New python executable in
/home/dnanexus/venv-py3.4/bin/python3.4
2017-11-16 07:09:24 asset_checkqc STDOUT Also creating executable in
/home/dnanexus/venv-py3.4/bin/python
2017-11-16 07:09:24 asset_checkqc STDOUT Installing setuptools, pip,
wheel...done.
2017-11-16 07:09:24 asset_checkqc STDOUT Running virtualenv with
interpreter /usr/bin/python3.4
2017-11-16 07:09:24 asset_checkqc STDOUT source venv-py3.4/bin/activate
2017-11-16 07:09:24 asset_checkqc STDOUT pip install -f
https://github.com/Illumina/interop/releases/tag/v1.1.1 interop
2017-11-16 07:09:24 asset_checkqc STDOUT Downloading/unpacking interop
2017-11-16 07:09:24 asset_checkqc STDOUT   Could not find a version that
satisfies the requirement interop (from versions: 1.1.1-Darwin-AppleClang,
1.1.1-Linux-GNU, 1.1.1-Windows-MSVC)
2017-11-16 07:09:24 asset_checkqc STDOUT Cleaning up...
2017-11-16 07:09:24 asset_checkqc STDOUT No distributions matching the
version for interop
2017-11-16 07:09:24 asset_checkqc STDOUT Storing debug log for failure in
/home/dnanexus/.pip/pip.log
2017-11-16 07:09:24 asset_checkqc STDOUT make: Leaving directory
`/home/dnanexus'
2017-11-16 07:09:24 asset_checkqc STDOUT

**Comment by johandahlberg** [comment]
I'm not familiar with the DNA Nexus Make files, but looking at the log above it looks like it is still trying to use python 3.4.

Could you try using this guide to make sure you have python 3.5 installed first?https://askubuntu.com/questions/682869/how-do-i-install-a-different-python-version-using-apt-get

If that does not work perhaps you could try starting by trying to update pip? I'm not sure exactly which version would be required, but this is what it looks like in the Ubuntu 14.04 virtual machine that I'm running:

```
(venv-py3.5) vagrant@vagrant-ubuntu-trusty-64:~$ pip --version
pip 9.0.1 from /home/vagrant/venv-py3.5/lib/python3.5/site-packages (python 3.5)
```

**Comment by avilella** [comment]
I updated my asset instructions now:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo rm -f /etc/apt/apt.conf.d/99dnanexus

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install -y python3.5

sudo apt-get install -y python3-pip
sudo pip3 install virtualenv
virtualenv --python=python3.5 venv-py3.5
source venv-py3.5/bin/activate
pip --version
pip install -f https://github.com/Illumina/interop/releases/tag/v1.1.1
interop
pip install checkqc
checkqc --version
```

It fails with pip, also via tar.gz python setup.py install, both cases
presumably now because it can't find interop:

```
Installed /usr/local/lib/python2.7/dist-packages/checkQC-1.1.2-py2.7.egg
Processing dependencies for checkQC==1.1.2
Searching for interop
Reading https://pypi.python.org/simple/interop/
Couldn't find index page for 'interop' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for interop
error: Could not find suitable distribution for Requirement.parse('interop')
```

**Comment by johanherman** [comment]
Hey @avilella. If you have Python2 and Python3 installed along each other then running `pip` will often still refer to the version 2 ecosystem, whereas `pip3` should use the version 3. 

I.e. in your list of commands above try running `pip3 --version`, `pip3 install -f https://github.com/Illumina/interop/releases/tag/v1.1.1 interop`, `pip3 install checkqc` instead.

Sometimes when environments have been mixed up incorrectly it can also work to call the Python binary and load the pip module manually (instead of going through the pip wrapper). I.e. a `pip3 install foo` would become `python3 -m pip install foo`.

**Comment by johandahlberg** [comment]
Hi @avilella!
Did you manage to resolve this issue, or is there something we can do to help?

**Comment by avilella** [comment]
I updated the Makefile I am using to try to get checkQC working on DNAnexus
(this is the platform I am using). After updating some pip for pip3
commands as per your latest reply, it seems it goes a bit further, but
still can't find interop:

```
2018-01-15 09:52:28 asset_checkqc STDOUT sudo pip3 install virtualenv
2018-01-15 09:52:28 asset_checkqc STDOUT Downloading/unpacking virtualenv
2018-01-15 09:52:28 asset_checkqc STDOUT Installing collected packages:
virtualenv
2018-01-15 09:52:28 asset_checkqc STDOUT Successfully installed virtualenv
2018-01-15 09:52:28 asset_checkqc STDOUT Cleaning up...
2018-01-15 09:52:28 asset_checkqc STDOUT virtualenv --python=python3.5
venv-py3.5 && \
2018-01-15 09:52:28 asset_checkqc STDOUT        source
venv-py3.5/bin/activate && \
2018-01-15 09:52:28 asset_checkqc STDOUT        sudo pip3 --version && \
2018-01-15 09:52:28 asset_checkqc STDOUT        sudo pip3 install -f
https://github.com/Illumina/interop/releases/tag/v1.1.1 interop && \
2018-01-15 09:52:28 asset_checkqc STDOUT        sudo pip3 install checkqc
&& \
2018-01-15 09:52:28 asset_checkqc STDOUT        checkqc --version
2018-01-15 09:52:28 asset_checkqc STDOUT Using base prefix '/usr'
2018-01-15 09:52:28 asset_checkqc STDOUT New python executable in
/home/dnanexus/venv-py3.5/bin/python3.5
2018-01-15 09:52:28 asset_checkqc STDOUT Also creating executable in
/home/dnanexus/venv-py3.5/bin/python
2018-01-15 09:52:28 asset_checkqc STDOUT Installing setuptools, pip,
wheel...done.
2018-01-15 09:52:28 asset_checkqc STDOUT Running virtualenv with
interpreter /usr/bin/python3.5
2018-01-15 09:52:28 asset_checkqc STDOUT pip 1.5.4 from
/usr/lib/python3/dist-packages (python 3.4)
2018-01-15 09:52:28 asset_checkqc STDOUT Downloading/unpacking interop
2018-01-15 09:52:28 asset_checkqc STDOUT   Could not find a version that
satisfies the requirement interop (from versions: 1.1.1-Darwin-AppleClang,
1.1.1-Linux-GNU, 1.1.1-Windows-MSVC)
2018-01-15 09:52:28 asset_checkqc STDOUT Cleaning up...
2018-01-15 09:52:28 asset_checkqc STDOUT No distributions matching the
version for interop
2018-01-15 09:52:28 asset_checkqc STDOUT Storing debug log for failure in
/home/dnanexus/.pip/pip.log
2018-01-15 09:52:28 asset_checkqc STDOUT make: Leaving directory
`/home/dnanexus'
2018-01-15 09:52:28 asset_checkqc STDOUT
```

**Comment by johandahlberg** [comment]
It seems that it is still using python 3.4 which is unsupported. Here is an idea which might force the correct binaries to be used throughout:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo rm -f /etc/apt/apt.conf.d/99dnanexus

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install -y python3.5

sudo apt-get install -y python3-pip
sudo pip3 install virtualenv
virtualenv --python=python3.5 venv-py3.5

/home/dnanexus/venv-py3.5/bin/pip3.5 install --upgrade pip
/home/dnanexus/venv-py3.5/bin/pip3.5 --version
/home/dnanexus/venv-py3.5/bin/pip3.5 install -f https://github.com/Illumina/interop/releases/tag/v1.1.1 interop
/home/dnanexus/venv-py3.5/bin/pip3.5 install checkqc
/home/dnanexus/venv-py3.5/bin/checkqc --version
```
Not very pretty, but explicitly pointing to the correct version binaries should hopefully make sure the correct  once are used all the way through.

**Comment by johandahlberg** [comment]
Hi @avilella !

The interop libraries are now available to install via PyPI. This might make it easier for you to install. We still require a python 3.5 as the minimum supported python version, though.

**Comment by avilella** [comment]
That sounds promising. What would be your recommended updated recipe from
above?

**Comment by johandahlberg** [comment]
Yes. But you can skip the `/home/dnanexus/venv-py3.5/bin/pip3.5 install -f https://github.com/Illumina/interop/releases/tag/v1.1.1 interop` part. The updated recipe should be something like this:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo rm -f /etc/apt/apt.conf.d/99dnanexus

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install -y python3.5

sudo apt-get install -y python3-pip
sudo pip3 install virtualenv
virtualenv --python=python3.5 venv-py3.5

/home/dnanexus/venv-py3.5/bin/pip3.5 install --upgrade pip
/home/dnanexus/venv-py3.5/bin/pip3.5 --version
/home/dnanexus/venv-py3.5/bin/pip3.5 install checkqc
/home/dnanexus/venv-py3.5/bin/checkqc --version
```

**Comment by johandahlberg** [comment]
Hi @avilella !
I'm just curious to hear if you got CheckQC working following the instructions above?

**Comment by avilella** [comment]
At this point, I am stuck not being able to see the checkQC in the system,
even though the installation instructions complete without complaint. Since
the installation is done with 'sudo -H', I can't figure out where does the
python virtual installation go and how to execute chcekQC.

I need to find out if DNAnexus is doing something weird or if it's just me
not understanding where is the binary going after installation.

Any guesses would be welcomed! Thanks

**Comment by johandahlberg** [comment]
I think it should be available from here `/home/dnanexus/venv-py3.5/bin/checkqc`. So if you point directly at that binary it should run.

**Comment by avilella** [comment]
I tested the pip install method on 16.04, which is now supported in DNAnexus, and it worked. The 14.04 still an issue, but less so with the 16.04 option.

**Comment by johandahlberg** [comment]
I'm happy to hear that this worked out.
