### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '... /Unaligned/Stats/Stats.json'

### ISSUE THREAD

**Issue by af8** [Molmed/checkQC#39]
Hi,

I am trying to use checkQC to parse results from a NovaSeq run.
There is no such Stats.json file, is it something specific to your local configuration at MolMed  ?

Or do I have to do something before launching checkQC ?

Best,
Anthony

**Comment by af8** [comment]
OK sorry about that, this is the file generated by bcl2fastq.

**Comment by johandahlberg** [comment]
Thank you for reporting this. I will make sure that there is some more informative messages in the log.
