### ISSUE TITLE
API docs does not get generate on readthedocs.io

### ISSUE THREAD

**Issue by johandahlberg** [Molmed/checkQC#63]
We are currently having some trouble generating the docs at readthedocs.io. This used to work, but then for reasons that are unknown to me it stopped working. 

I have previously added some code which I found here to make the API auto-build: https://github.com/rtfd/readthedocs.org/issues/1139 to make this work, however since that seemed to be what was causing the readthedocs build errors I "removed" it in this commit: https://github.com/Molmed/checkQC/commit/ad9c7b57d46fc4382a9a5ddfea0fd75302641b45 

The current state is that the normal documentation is up on readthedocs, while the API docs are missing. I don't have time to look further into this at the moment, so I'll leave this here as a note to myself once I get back to it. However should anyone else feel like picking up this issue up go ahead!

**Comment by roxyboy** [comment]
I am having a some what different but similar issue that the API docs don't update automatically to the new merged PRs.
